package.json
src/lib/components/auth/AuthWrapper.tsx
src/lib/components/hall/components/CreateRoom.tsx
src/lib/components/hall/components/JoinRoom.tsx
src/lib/components/layout/FullScreenLoading.tsx
src/lib/components/layout/index.tsx
src/lib/components/room/JoinContainer.tsx
src/lib/components/room/RoomContainer.tsx
src/lib/components/room/components/ControllerWrapper.tsx
src/lib/components/room/components/CurrentVotesWrapper.tsx
src/lib/components/room/components/PointWrapper.tsx
src/lib/components/room/components/RoomHeader.tsx
src/lib/components/room/components/VoteWrapper.tsx
src/lib/components/ui/SpokerButton.tsx
src/lib/components/ui/SpokerInput.tsx
src/lib/components/ui/SpokerRadioBox.tsx
src/lib/components/ui/SpokerWrapperGrid.tsx
src/lib/services/firebase/config.ts
src/lib/services/firebase/room.ts
src/lib/types/RawDB.ts
src/lib/types/room.ts
src/pages/_app.tsx
src/pages/_document.tsx
yarn.lock

chore: update packages, eslint-config-sznm 0.2.1

---

commitlint.config.js
package.json
src/lib/components/auth/AuthPopover.tsx
src/lib/components/auth/AuthProvider.tsx
src/lib/components/room/RoomContainer.tsx
src/lib/components/room/components/CurrentVotesWrapper.tsx
src/lib/components/room/components/VoteWrapper.tsx
src/lib/services/firebase/auth.ts
src/lib/services/firebase/config.ts
src/lib/services/firebase/room.ts
yarn.lock

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/17046154/151428299-a0ddacc0-b9b2-424d-943f-cf3b5f1a70b4.png) | ![image](https://user-images.githubusercontent.com/17046154/151428551-f39f6fab-79e3-47be-b77b-27e7fca02a8e.png) |

refactor(services): upgrade firebase sdk to v9 modular

---

.vscode/launch.json

https://nextjs.org/docs/advanced-features/debugging#debugging-with-vs-code

chore: add launch.json file

---

package.json
src/lib/components/room/CurrentVotesWrapper.tsx
src/lib/constants/wrapperkeys.ts
src/lib/pages/room/hooks.ts
src/lib/pages/room/utils.ts
yarn.lock

feat(room): 🎉  add confetti when show vote

---

CHANGELOG.md
package.json
src/lib/components/room/PointWrapper.tsx

release v1.11.2

---

.all-contributorsrc
CONTRIBUTING.md
README.md
package.json
yarn.lock

chore: setup all-contributors ✨

---

CHANGELOG.md
package.json
src/lib/components/room/header/hooks.ts

Release v1.11.4

---

src/lib/components/auth/AuthPopover.tsx
src/lib/services/firebase/room/update/disconnectUser.ts

fix(auth): fix logout through popover issue

---

src/lib/components/auth/AuthPopover.tsx
src/lib/components/support/SupportContent.tsx
src/lib/layout/Header.tsx
src/lib/styles/theme/components/index.ts
src/lib/styles/theme/components/popover.ts

refactor: adjust UI

---

CHANGELOG.md
package.json
yarn.lock

Release v1.12.2

---

src/lib/styles/theme/config.ts
src/lib/styles/theme/index.ts

refactor(layout): enable transition on change theme

---

.env.example
CHANGELOG.md
package.json
src/lib/services/firebase/config.ts
src/lib/styles/theme/config.ts
src/lib/styles/theme/index.ts
src/pages/_document.tsx

Release v1.12.3

---

.gitignore
.husky/pre-commit
.husky/pre-push
package.json
turbo.json
yarn.lock

chore: setup turbo

---

.gitignore
.husky/pre-commit
.husky/pre-push
package.json
turbo.json
yarn.lock

Add turbo setup

---

CHANGELOG.md
package.json
src/lib/components/shared/Twemoji.tsx

Release v1.12.5

---

src/lib/components/shared/Twemoji.tsx

- problem: maxcdn down
- ref: https://github.com/twitter/twemoji/issues/580

refactor: use jsdelivr as twemoji base

---

CHANGELOG.md
package.json
src/lib/layout/Footer.tsx

Release v1.12.7

---

src/lib/components/support/SupportCTA.tsx
src/lib/layout/Footer.tsx
src/lib/layout/Header.tsx

refactor: adjust support button

---

CHANGELOG.md
package.json
src/lib/components/support/SupportCTA.tsx
src/lib/layout/Footer.tsx
src/lib/layout/Header.tsx
yarn.lock

Release v1.12.8

---

CHANGELOG.md
package.json
yarn.lock

Release v1.12.9

---

CHANGELOG.md
package.json
turbo.json

Release v1.12.10

---

sentry.edge.config.js
src/lib/components/auth/AuthPopover.tsx
src/lib/components/room/CurrentVotesWrapper.tsx
src/lib/components/room/TaskList/index.tsx
src/lib/components/room/VoteWrapper.tsx
src/lib/hooks/useRoomListener.ts
src/lib/hooks/useRoomPoint.ts
src/lib/hooks/useVote.ts
src/lib/layout/useAuthObserver.ts
src/lib/pages/room/index.tsx
src/lib/stores/auth.ts
src/lib/stores/room.ts

refactor: adjust zustand import

---

commitlint.config.js
sentry.client.config.js

chore(sentry): configure session replay

---

CHANGELOG.md
commitlint.config.js
package.json
sentry.client.config.js

Release v1.13.1

---

CHANGELOG.md
commitlint.config.js
package.json
src/lib/styles/theme/colors.ts
src/lib/styles/theme/index.ts

Release v1.13.2

---

CHANGELOG.md
package.json
src/lib/components/hall/components/JoinRoom.tsx
src/lib/components/room/TaskList/index.tsx
src/lib/components/shared/SpokerWrapperGrid.tsx
src/lib/layout/index.tsx

Release v1.13.3

---

src/lib/components/auth/AuthPopover.tsx
src/lib/components/shared/SpokerLogo/index.tsx
src/lib/components/support/SupportCTA.tsx
src/lib/layout/Footer.tsx
src/lib/layout/FullScreenLoading.tsx
src/lib/layout/Header.tsx
src/lib/layout/ThemeToggle.tsx
src/lib/pages/auth/index.tsx
src/lib/pages/hall/index.tsx
tools/generateRules.ts

feat(layout): revamp footer

---

src/lib/components/auth/AuthPopover.tsx
src/lib/components/auth/AuthWrapper.tsx
src/lib/components/auth/style.ts
src/lib/components/support/SupportCTA.tsx
src/lib/layout/ThemeToggle.tsx

feat(auth): adjust auth wrapper modal appearance

---

CHANGELOG.md
package.json
src/lib/components/auth/AuthPopover.tsx
src/lib/components/auth/AuthWrapper.tsx
src/lib/components/auth/Login/index.tsx
src/lib/components/auth/style.ts
src/lib/components/shared/SpokerLogo/index.tsx
src/lib/components/support/SupportCTA.tsx
src/lib/layout/Footer.tsx
src/lib/layout/FullScreenLoading.tsx
src/lib/layout/Header.tsx
src/lib/layout/ThemeToggle.tsx
src/lib/pages/auth/index.tsx
src/lib/pages/hall/index.tsx
src/lib/pages/home/index.tsx
tools/generateRules.ts

Release v1.15.0

---

.npmrc
CHANGELOG.md
package.json

- ref: https://pnpm.io/cli/run#differences-with-npm-run

chore: enable pre/post script for pnpm

---

next-seo.config.js
src/lib/pages/hall/index.tsx
src/lib/pages/home/index.tsx
src/pages/home.ts

feat(pages): add highlighted feature section in home page

---

CHANGELOG.md
package.json
sentry.client.config.js

Release v1.16.1

---

CHANGELOG.md
package.json
pnpm-lock.yaml
renovate.json

Release v1.16.2

---

CHANGELOG.md
additional.d.ts
package.json
pnpm-lock.yaml
src/lib/components/auth/SignInProviders.tsx
src/lib/components/room/ControllerWrapper.tsx
src/lib/components/room/CurrentVotesWrapper.tsx
src/lib/components/room/TaskList/TaskItem.tsx
src/lib/components/room/VoteWrapper.tsx
src/lib/components/room/header/hooks.ts
src/lib/hooks/useRoomListener.ts
src/lib/pages/join/index.tsx
src/lib/utils/trackEvent.ts
tsconfig.json

Release v1.16.3

---

pnpm-lock.yaml

chore(deps): bump @babel/traverse from 7.23.0 to 7.23.2 (#206)

---

.github/dependabot.yml
.husky/pre-push
package.json
pnpm-lock.yaml
renovate.json

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>### Description

sync dev to main

---

.github/dependabot.yml
renovate.json

chore: pin chakra-ui version

---

.eslintrc.json
eslint.config.mjs
package.json
pnpm-lock.yaml
src/instrumentation.ts
src/lib/components/twemoji.tsx
src/lib/services/firebase/rules.ts
src/pages/_error.tsx

chore: eslint v9
